= My Karate Experiments

Karate is a truly DSL to test web apis - see https://github.com/intuit/karate.

This repository is my sandbox, a place where I put my experiments.

== Motivation

Karate offers already https://github.com/intuit/karate/tree/master/karate-demo[many examples and demos] but as everybody should know:

> There is no better teacher than experience itself

That's why I create my own little experiments. I try to use the https://popcornflow.com[popcornflow] to structure experiments and having
expectations upfront. Comparing my expectations with that what really happened enables me to learn.

== Gatling Setup

`src/test/scala` contains gatling tests and these tests can be executed with the `gatlingRun` task.

The karate environment can be changed as usual.

Example:

----
gradle gatlingRun -Dkarate.env=DEV
----

== Lessons Learned

[TIP]
====
Use Groovy to call karate features

Calling karate features from Groovy is a nice fit.
Because of groovy native support for lists and maps, it plays nicely together with the karate json format.

Checkout link:src/test/groovy/com/github/peterquiel/karate/experiment/CallFeatureFromJavaTest.groovy[CallFeatureFromJavaTest.groovy]
